name: STATUS CI/CD

on:
  push:
    branches: [main]
    paths:
      - 'backend/**'

env:
  BACKEND_IMAGE: service-monitor-backend
  APP_NAME: service-monitor-backend  # Added missing env var
  DOCKER_TAG: ${{ github.sha }}     # Added immutable tag
  K8S_NAMESPACE: service-monitor    # Added namespace var

jobs:
  build-test-deploy:
    runs-on: ubuntu-22.04

    steps:
    # ----------------------------------
    # 1. SETUP ENVIRONMENT
    # ----------------------------------
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Start Minikube
      uses: manusa/actions-setup-minikube@v2.7.0
      with:
        driver: docker
        kubernetes-version: 'stable'
        container-runtime: containerd

    # ----------------------------------
    # 2. BUILD & TEST
    # ----------------------------------
    - name: Set up Docker for Minikube
      run: |
        eval $(minikube docker-env)
        echo "DOCKER_HOST=$(minikube ip):2376" >> $GITHUB_ENV

    - name: Build Docker image
      run: |
        docker build \
          --tag ${{ env.BACKEND_IMAGE }}:${{ github.sha }} \
          --tag ${{ env.BACKEND_IMAGE }}:latest \
          --file ./backend/Dockerfile \
          ./backend
      
    - name: Run Tests
      run: |
        echo "All tests passed"  # Placeholder for real tests
        echo "TEST_STATUS=pass" >> $GITHUB_ENV

    # ----------------------------------
    # 3. DEPLOY
    # ----------------------------------
    - name: Deploy
      if: env.TEST_STATUS == 'pass'
      run: |
        kubectl apply -f backend/deployment.yaml -n ${{ env.K8S_NAMESPACE }}
        kubectl apply -f backend/service.yaml -n ${{ env.K8S_NAMESPACE }}
        echo "Deployment completed"
        
        # Wait for rollout
        kubectl rollout status deployment/${{ env.APP_NAME }}-deployment -n ${{ env.K8S_NAMESPACE }} --timeout=120s

    # ----------------------------------
    # 4. VERIFICATION
    # ----------------------------------
    - name: Verify deployment
      run: |
        echo "=== DEPLOYMENT STATUS ==="
        kubectl get deployments -n ${{ env.K8S_NAMESPACE }} -o wide
        
        echo "\n=== SERVICE ENDPOINTS ==="
        minikube service ${{ env.APP_NAME }}-service -n ${{ env.K8S_NAMESPACE }} --url
        
        echo "\n=== POD LOGS ==="
        kubectl logs -l app=${{ env.APP_NAME }} -n ${{ env.K8S_NAMESPACE }} --tail=50